import React, { useState, useRef } from 'react';
import {
  ShieldCheck, Cookie, Lock, X, ExternalLink, Check, AlertCircle,
  Loader2, Sparkles, Trash2, Upload, Download, FileText, Clipboard
} from 'lucide-react';
import { api } from '../../services/api';

export default function CookieModal({
  isOpen,
  onClose,
  onSuccess,
  existingCookieCount = 0
}) {
  const [cookieText, setCookieText] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [successMsg, setSuccessMsg] = useState(null);
  const fileInputRef = useRef(null);

  if (!isOpen) return null;

  const handleSave = async () => {
    if (!cookieText.trim()) {
      setError('Please paste or upload your YouTube cookies before continuing.');
      return;
    }

    setIsSubmitting(true);
    setError(null);
    setSuccessMsg(null);

    try {
      const res = await api.saveUserCookies(cookieText.trim());
      setSuccessMsg(`Successfully loaded ${res.count} verification cookies!`);
      if (onSuccess) onSuccess(res.count);
      setTimeout(() => {
        onClose();
      }, 1000);
    } catch (err) {
      setError(err.message || 'Failed to parse cookies. Ensure valid Netscape or JSON format.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handlePasteClipboard = async () => {
    try {
      const text = await navigator.clipboard.readText();
      if (text) {
        setCookieText(text);
        setError(null);
      }
    } catch {
      // Clipboard access denied, user can paste manually
    }
  };

  const handleFileUpload = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result;
      if (typeof content === 'string') {
        setCookieText(content);
        setError(null);
        setSuccessMsg(`Loaded "${file.name}" (${file.size} bytes). Click "Save & Continue" to activate.`);
      }
    };
    reader.onerror = () => {
      setError('Failed reading file. Please paste the text manually.');
    };
    reader.readAsText(file);
    // Reset file input so same file can be re-selected if needed
    e.target.value = '';
  };

  const handleDownloadTemplate = () => {
    const templateContent = [
      '# Netscape HTTP Cookie File',
      '# http://curl.haxx.se/rfc/cookie_spec.html',
      '# This is a sample format generated by TuneFetch for reference.',
      '.youtube.com\tTRUE\t/\tTRUE\t2147483647\tLOGIN_INFO\taf7a8sdf7asd...',
      '.youtube.com\tTRUE\t/\tTRUE\t2147483647\t__Secure-3PSID\tasdf1234...',
      '.youtube.com\tTRUE\t/\tTRUE\t2147483647\tVISITOR_INFO1_LIVE\txxYYzz123...',
      ''
    ].join('\n');

    const blob = new Blob([templateContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'sample_youtube_cookies.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 1000,
        background: 'rgba(0, 0, 0, 0.82)',
        backdropFilter: 'blur(10px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px',
        animation: 'fadeIn 0.25s ease-out'
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: 'linear-gradient(135deg, rgba(18, 22, 34, 0.96) 0%, rgba(10, 13, 20, 0.98) 100%)',
          border: '1px solid rgba(255, 255, 255, 0.12)',
          boxShadow: '0 24px 60px rgba(0, 0, 0, 0.6), 0 0 40px rgba(29, 185, 84, 0.15)',
          borderRadius: '20px',
          width: '100%',
          maxWidth: '640px',
          maxHeight: '94vh',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
          animation: 'scaleUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)'
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div
          style={{
            padding: '20px 24px 16px',
            borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
            display: 'flex',
            alignItems: 'flex-start',
            justifyContent: 'space-between',
            gap: '16px'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
            <div
              style={{
                width: '46px',
                height: '46px',
                borderRadius: '12px',
                background: 'linear-gradient(135deg, rgba(29, 185, 84, 0.25), rgba(30, 215, 96, 0.1))',
                border: '1px solid rgba(29, 185, 84, 0.4)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: '#1ed760'
              }}
            >
              <Cookie size={24} />
            </div>
            <div>
              <h2 style={{ margin: 0, fontSize: '18px', fontWeight: 700, color: 'var(--text-primary)', letterSpacing: '-0.02em' }}>
                YouTube Verification Cookies
              </h2>
              <p style={{ margin: '3px 0 0', fontSize: '13px', color: 'var(--text-secondary)' }}>
                Bypasses YouTube bot verification on cloud hosting for uninterrupted 320kbps downloads.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="icon-btn"
            style={{
              background: 'rgba(255, 255, 255, 0.06)',
              border: 'none',
              borderRadius: '50%',
              width: '32px',
              height: '32px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'var(--text-muted)',
              cursor: 'pointer'
            }}
            title="Close"
          >
            <X size={17} />
          </button>
        </div>

        {/* Modal Body */}
        <div style={{ padding: '20px 24px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '14px' }}>
          {/* Privacy Guarantee Box */}
          <div
            style={{
              background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.12) 0%, rgba(6, 78, 59, 0.2) 100%)',
              border: '1px solid rgba(52, 211, 153, 0.35)',
              borderRadius: '14px',
              padding: '12px 16px',
              display: 'flex',
              gap: '12px',
              alignItems: 'flex-start'
            }}
          >
            <ShieldCheck size={20} style={{ color: '#34d399', flexShrink: 0, marginTop: '2px' }} />
            <div style={{ fontSize: '12.5px', color: 'rgba(255, 255, 255, 0.9)', lineHeight: 1.5 }}>
              <strong style={{ color: '#6ee7b7', display: 'block', marginBottom: '2px' }}>
                100% Privacy Guarantee • Ephemeral Session Encryption
              </strong>
              Your cookies are encrypted and held strictly for your active download session.
              You can clear them at any time using the <strong>Clear Cookies</strong> button or disconnecting.
            </div>
          </div>

          {/* 3-Step Guide */}
          <div
            style={{
              background: 'rgba(255, 255, 255, 0.03)',
              border: '1px solid rgba(255, 255, 255, 0.06)',
              borderRadius: '12px',
              padding: '12px 16px',
              fontSize: '12px',
              color: 'var(--text-secondary)',
              lineHeight: 1.6
            }}
          >
            <div style={{ fontWeight: 600, color: 'var(--text-primary)', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Sparkles size={14} style={{ color: '#1ed760' }} />
              How to get your cookies in 20 seconds:
            </div>
            <ol style={{ margin: '4px 0 0', paddingLeft: '18px' }}>
              <li>Open <a href="https://www.youtube.com" target="_blank" rel="noreferrer" style={{ color: '#38bdf8', textDecoration: 'none' }}>youtube.com</a> in your browser.</li>
              <li>Use the free browser extension <strong>"Get cookies.txt LOCALLY"</strong> or <strong>"Cookie-Editor"</strong>.</li>
              <li>Click <strong>Export</strong> and either upload the file or paste the text below.</li>
            </ol>
          </div>

          {/* Action Toolbar (Upload / Paste / Sample) */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}>
            <label style={{ fontSize: '13px', fontWeight: 600, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Lock size={13} style={{ color: '#a78bfa' }} />
              Cookies Content (Netscape or JSON):
            </label>

            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}>
              {/* Hidden file input */}
              <input
                type="file"
                accept=".txt"
                ref={fileInputRef}
                onChange={handleFileUpload}
                style={{ display: 'none' }}
              />

              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                style={{
                  background: 'rgba(56, 189, 248, 0.12)',
                  border: '1px solid rgba(56, 189, 248, 0.3)',
                  borderRadius: '6px',
                  padding: '4px 10px',
                  fontSize: '11px',
                  color: '#7dd3fc',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px',
                  transition: 'all 0.2s'
                }}
                title="Upload cookies.txt file directly from your computer"
              >
                <Upload size={12} /> Upload File (.txt)
              </button>

              <button
                type="button"
                onClick={handlePasteClipboard}
                style={{
                  background: 'rgba(255, 255, 255, 0.08)',
                  border: '1px solid rgba(255, 255, 255, 0.12)',
                  borderRadius: '6px',
                  padding: '4px 10px',
                  fontSize: '11px',
                  color: 'var(--text-primary)',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px',
                  transition: 'all 0.2s'
                }}
              >
                <Clipboard size={12} /> Paste Clipboard
              </button>

              <button
                type="button"
                onClick={handleDownloadTemplate}
                style={{
                  background: 'rgba(255, 255, 255, 0.05)',
                  border: '1px solid rgba(255, 255, 255, 0.08)',
                  borderRadius: '6px',
                  padding: '4px 8px',
                  fontSize: '11px',
                  color: 'var(--text-muted)',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px'
                }}
                title="Download reference template file"
              >
                <Download size={11} /> Sample Format
              </button>

              {cookieText && (
                <button
                  type="button"
                  onClick={() => setCookieText('')}
                  style={{
                    background: 'none',
                    border: 'none',
                    color: 'var(--text-muted)',
                    fontSize: '11px',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '4px'
                  }}
                >
                  <Trash2 size={11} /> Clear
                </button>
              )}
            </div>
          </div>

          {/* Textarea for Cookies */}
          <div>
            <textarea
              rows={7}
              placeholder={`# Netscape HTTP Cookie File\n# Or choose "Upload File (.txt)" above to select your downloaded cookies.txt\n.youtube.com\tTRUE\t/\tTRUE\t2147483647\tLOGIN_INFO\tabc123...\n.youtube.com\tTRUE\t/\tTRUE\t2147483647\t__Secure-3PSID\txyz456...`}
              value={cookieText}
              onChange={(e) => {
                setCookieText(e.target.value);
                setError(null);
              }}
              style={{
                width: '100%',
                padding: '12px 14px',
                background: 'rgba(0, 0, 0, 0.35)',
                border: error ? '1px solid #ef4444' : '1px solid rgba(255, 255, 255, 0.12)',
                borderRadius: '12px',
                color: '#e2e8f0',
                fontSize: '12px',
                fontFamily: 'monospace',
                lineHeight: 1.4,
                resize: 'vertical',
                outline: 'none',
                transition: 'border-color 0.2s, box-shadow 0.2s',
                boxShadow: error ? '0 0 10px rgba(239, 68, 68, 0.2)' : 'none'
              }}
            />
            {cookieText.length > 0 && (
              <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '4px', textAlign: 'right' }}>
                {cookieText.split('\n').filter(l => l.trim()).length} lines detected
              </div>
            )}
          </div>

          {/* Feedback Messages */}
          {error && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 14px', borderRadius: '8px', background: 'rgba(239, 68, 68, 0.12)', border: '1px solid rgba(239, 68, 68, 0.3)', color: '#fca5a5', fontSize: '12.5px' }}>
              <AlertCircle size={16} style={{ flexShrink: 0 }} />
              <span>{error}</span>
            </div>
          )}

          {successMsg && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 14px', borderRadius: '8px', background: 'rgba(16, 185, 129, 0.15)', border: '1px solid rgba(16, 185, 129, 0.35)', color: '#6ee7b7', fontSize: '12.5px' }}>
              <Check size={16} style={{ flexShrink: 0 }} />
              <span>{successMsg}</span>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div
          style={{
            padding: '16px 24px 20px',
            borderTop: '1px solid rgba(255, 255, 255, 0.08)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '12px',
            background: 'rgba(0, 0, 0, 0.2)'
          }}
        >
          <button
            type="button"
            onClick={onClose}
            style={{
              padding: '10px 18px',
              background: 'rgba(255, 255, 255, 0.06)',
              border: '1px solid rgba(255, 255, 255, 0.1)',
              borderRadius: '10px',
              color: 'var(--text-secondary)',
              fontSize: '13px',
              fontWeight: 500,
              cursor: 'pointer',
              transition: 'background 0.2s'
            }}
          >
            Skip (Try Without Cookies)
          </button>

          <button
            type="button"
            disabled={isSubmitting || !cookieText.trim()}
            onClick={handleSave}
            style={{
              padding: '10px 24px',
              background: isSubmitting || !cookieText.trim()
                ? 'rgba(29, 185, 84, 0.35)'
                : 'linear-gradient(135deg, #1ed760 0%, #16a34a 100%)',
              border: 'none',
              borderRadius: '10px',
              color: isSubmitting || !cookieText.trim() ? 'rgba(255, 255, 255, 0.6)' : '#000',
              fontWeight: 700,
              fontSize: '13px',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              cursor: isSubmitting || !cookieText.trim() ? 'not-allowed' : 'pointer',
              boxShadow: isSubmitting || !cookieText.trim() ? 'none' : '0 4px 18px rgba(29, 185, 84, 0.35)',
              transition: 'all 0.2s'
            }}
          >
            {isSubmitting ? (
              <>
                <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} />
                Verifying & Saving...
              </>
            ) : (
              <>
                <Check size={16} />
                Save & Continue to Downloads
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
